model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  success_callbacks: ["langfuse"]
  failure_callbacks: ["langfuse"]
  # ↓↓↓ 【重要】ここでPythonファイルのインスタンス変数を指定します ↓↓↓
  callbacks: ai_platform_litellm.custom_hooks.proxy_handler_instance

mcp_servers:
  my_hello_mcp:
    url: "http://mcp-server:5001/mcp"   # FastMCPの Streamable HTTP のデフォルトパス
    type: "http"                        # LiteLLM側で Streamable HTTP を指定する値
    extra_headers: ["Authorization", "litellm-api-key", "test"]  # ここで指定したヘッダーは、LiteLLMからMCPサーバーに転送される