services:
  executor:
    build: .
    image: my-executor:latest
    container_name: executor-service
    restart: always
    environment:
      - HOST_PROJECTS_ROOT=/home/user/ai-platform/data/dify/projects # ホスト側の絶対パスを指定
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # エグゼキューター自体もこのフォルダにアクセスできる必要がある
      - ../../data/dify/projects:/home/user/ai-platform/data/dify/projects
    networks:
      - ai_platform_net

networks:
  ai_platform_net:
    external: true