services:
   squid:
      image: ubuntu/squid:latest
      restart: always
      volumes:
         - ./squid.conf:/etc/squid/squid.conf:ro
      # NOTE: 社内LANからSquidを叩く必要がないなら ports 公開は不要。
      # ports:
      #   - "3128:3128"
      networks:
         - ai_platform_internal
         - ai_platform_egress

networks:
   ai_platform_internal:
      name: ai_platform_internal
      driver: bridge
      internal: true

   ai_platform_egress:
      name: ai_platform_egress
      driver: bridge
