general_settings:
  database_url: "postgresql://postgres:postgres@postgres:5432/postgres"
  # allow_requests_on_db_unavailable: true
model_list:
  - model_name: poc-chat-model
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: poc-embedding-model
    litellm_params:
      model: openai/text-embedding-3-large
      api_key: os.environ/OPENAI_API_KEY
  - model_name: poc-fast-model
    litellm_params:
      model: openai/gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  # ↓↓↓ 【重要】ここでPythonファイルのインスタンス変数を指定します ↓↓↓
  callbacks: ai_platform_litellm.hook.custom_hooks.proxy_handler_instance

mcp_servers:
  my_hello_mcp:
    url: "http://mcp-server-test1:5101/mcp"   # FastMCPの Streamable HTTP のデフォルトパス
    type: "http"                        # LiteLLM側で Streamable HTTP を指定する値
    extra_headers: ["Authorization", "litellm-api-key", "test"]  # ここで指定したヘッダーは、LiteLLMからMCPサーバーに転送される